#%RAML 1.0 NamedExample
[
    {
        "customerName": "ravi",
        "bank": "HDFC",
        "type": "savings",
        "branchName": "BLR",
        "accountNum": "54326781234",
        "ifscCode": "HDFC10034",
        "mailId": "ravi@gmail.com",
        "cardStatus": "locked"
    },
    {
        "customerName": "Narsing",
        "bank": "SBI",
        "type": "savings",
        "branchName": "vizag",
        "accountNum": "8974562356",
        "ifscCode": "SBI0003",
        "mailId": "narsingbeesetti22@gmail.com",
        "cardStatus": "Locked"
    }
]