#%RAML 1.0 NamedExample
{
            "user": "admin",
            "password": "admin",
            "accountNum": "1234567896",
            "bank": "HDFC",
            "accountStatus": "Unlock"
          }